M48
; DRILL file {KiCad (6.0.1)} date Sun Dec 10 20:53:16 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-12-10T20:53:16-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.1)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0984
%
G90
G05
T1
X2.0866Y-2.0866
X2.0866Y-2.7953
X4.2362Y-2.0866
X4.2362Y-2.7953
T0
M30
