@echo off

set file_path=.\Spankulator\version_num.h

echo This will set the Spankulator software release number in %file_path%

if not defined SPANK_RELEASE_NUM goto ask

echo The current release number is: %SPANK_RELEASE_NUM%

:ask
set /p release_num=What's the NEW software release number?

set /p ans=That's %release_num%, eh? (y/n)

if %ans% == n goto end
setx SPANK_RELEASE_NUM %release_num%

echo // *** Warning! *** Do not edit this file. Use release.bat instead. > %file_path%
echo #ifndef VERSION_NUM_h >> %file_path%
echo #define VERSION_NUM_h >> %file_path%
echo. >> %file_path%
echo #define VERSION_NUM "v%release_num%" >> %file_path%
echo. >> %file_path%
echo #endif >> %file_path%

call make.bat

copy .\out\Spankulator.ino.bin updater

".\7z" a -r .\releases\spankulator_updater_%release_num%.zip updater -x!updater.sh

REM Create a tar archive using 7-Zip for the Mac/Linux users
".\7z" a -ttar archive.tar ./updater/* -x!update.bat

REM Compress the tar archive into .gz format using 7-Zip
".\7z" a -tgzip .\archive.tar.gz ./archive.tar

".\7z" a .\releases\spankulator_updater_%release_num%.tar.zip ./archive.tar.gz

REM Delete the intermediate .tar file
del archive.tar
del archive.tar.gz
:end
echo Goodbye!

pause

