@echo off

set file_path=.\Spankulator\version_num.h

echo This will set the Spankulator software release number in %file_path%

if not defined SPANK_RELEASE_NUM goto ask

echo The current release number is: %SPANK_RELEASE_NUM%

:ask
set /p release_num=What's the NEW software release number?

set /p ans=That's %release_num%, eh? (y/n)

if %ans% == n goto end
setx SPANK_RELEASE_NUM %release_num%

echo // *** Warning! *** Do not edit this file. Use release.bat instead. > %file_path%
echo #ifndef VERSION_NUM_h >> %file_path%
echo #define VERSION_NUM_h >> %file_path%
echo. >> %file_path%
echo #define VERSION_NUM "v%release_num%" >> %file_path%
echo. >> %file_path%
echo #endif >> %file_path%

call make.bat

copy .\out\Spankulator.ino.bin updater

"C:\Program Files\7-Zip\7z.exe" a -r .\releases\spankulator_updater_%release_num%.zip updater 

:end
echo Goodbye!

pause

